project:
  type: website
  output-dir: docs

website:
  title: "mtmx"
  site-url: https://mtmx.github.io/
  repo-url: https://github.com/mtmx/mtmx.github.io
  open-graph: true
  favicon: images/img_campagne_rond.png
  twitter-card:
    creator: "@matamix"
    card-style: summary_large_image
    image: images/img_campagne_rond.png
  navbar:
    logo: images/img_campagne_rond.png
    href: https://mtmx.github.io/
    background: "#bacdcb"
    right:
      - text: "Des posts"
        file: index.qmd
      - bots.qmd
      - about.qmd
      - icon: github
        href: https://github.com/mtmx
      - icon: twitter
        href: https://twitter.com/matamix
format:
  html:
    theme: 
      light: minty
      dark: darkly
    highlight-style: arrow
    fig-dpi: 600
    fig-align: center
    fig-width: 8
    fig-asp: 0.618 # 1 / pi
    fig-format: png


