project:
  type: website

website:
  title: "mtmx"
  site-url: https://mtmx.netlify.app/
  repo-url: https://github.com/mtmx/mtmx
  open-graph: true
  twitter-card:
    creator: "@matamix"
    card-style: summary_large_image
  navbar:
    background: "#bacdcb"
    right:
      - bots.qmd
      - about.qmd
      - icon: github
        href: https://github.com/mtmx
      - icon: twitter
        href: https://twitter.com/matamix
format:
  html:
    theme: minty
    highlight-style: arrow
    fig-dpi: 600
    fig-align: center
    fig-width: 8
    fig-asp: 0.618 # 1 / pi
    fig-format: png


